name = "retrovault-cc"
keep_vars = true
main = ".output/server/index.mjs"
compatibility_date = "2026-05-07"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

assets = { directory = ".output/public" }

routes = [
  { pattern = "retrovault.cc", zone_name = "retrovault.cc", custom_domain = true },
  { pattern = "www.retrovault.cc", zone_name = "retrovault.cc", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "retro-vault"
database_id = "24086795-335c-4fbc-92dc-6e5d5350ecea"

[[kv_namespaces]]
binding = "RETROVAULT"
id = "6c000acaef05427eab3eefd994db15ac"

# [[r2_buckets]]
# binding = "CDN"
# bucket_name = "aifindr-cdn"

[vars]
API_BASE = "https://retrovault.cc"
# md5(retrovault.cc) = 273be4be4de0339309f670bee6789807
NUXT_OG_IMAGE_SECRET = "273be4be4de0339309f670bee6789807"
ADMIN_EMAIL="kbmjj123@gmail.com"

# [triggers]
# crons = ["0 9 * * *"]
