-- seed-dev.sql — 本地开发种子数据
-- 生成时间: 2026-07-14T23:09:38.678Z
-- 游戏数量: 14
-- 覆盖平台: nes, snes, game-boy-advance, genesis, arcade, nintendo-64, playstation

BEGIN TRANSACTION;

INSERT INTO games (
  slug, title, platform, year, genre, developer, publisher, series,
  isHack, language, coverUrl, imageUrl, defaultRom,
  ejsCore, ejsBiosUrl,
  tags, description, langs, roms,
  status, source, createdAt, updatedAt
) VALUES (
  'golf',
  'Golf',
  'nes',
  1985,
  'sports',
  'nintendo',
  'nintendo',
  'golf',
  0,
  'English',
  'golf/golf.webp',
  'https://classicgamezone.com/games/covers/nes/golf.webp',
  'golf/golf.nes',
  'nes',
  '',
  '["sports","8-bit","golf","competitive"]',
  'Golf for NES is Nintendo''s first golf simulation game, released as a launch title for the Nintendo Entertainment System in 1985. This simple yet challenging game established the template for future golf video games with its intuitive three-click swing mechanic and overhead course view.',
  '{"en":{"title":"Golf","description":"Golf for NES is Nintendo''s first golf simulation game, released as a launch title for the Nintendo Entertainment System in 1985. This simple yet challenging game established the template for future golf video games with its intuitive three-click swing mechanic and overhead course view.","longDescription":["As one of the earliest sports simulations on NES, Golf introduced millions to video game golf with its accessible controls and realistic physics for the time.","The game features six 18-hole courses with varying terrain including sand traps, water hazards, and elevation changes that affect ball trajectory.","Players can compete in stroke play or match play modes, with support for two players taking turns (no simultaneous play).","Golf was one of the first NES games to feature battery backup for saving progress, allowing players to complete full 18-hole rounds over multiple sessions."],"controls":{"D-Pad":"Aim/select club","A Button":"Start swing/power meter","B Button":"Cancel shot","Start":"Pause/confirm selection","Select":"Change view"}}}',
  '[{"lang":"default","filename":"golf.nes","localPath":"data/games/golf/golf.nes","r2Key":"golf/golf.nes","url":"https://classicgamezone.com/games/roms/nes/golf.nes","size":24592,"status":"downloaded"}]',
  'published',
  'classicgamezone.com',
  '2026-07-14 23:09:38',
  '2026-07-14 23:09:38'
);
INSERT INTO games (
  slug, title, platform, year, genre, developer, publisher, series,
  isHack, language, coverUrl, imageUrl, defaultRom,
  ejsCore, ejsBiosUrl,
  tags, description, langs, roms,
  status, source, createdAt, updatedAt
) VALUES (
  'who-framed-roger-rabbit-nes',
  'Who Framed Roger Rabbit',
  'nes',
  1989,
  'action-adventure',
  'rare',
  'ljn',
  'who-framed-roger-rabbit',
  0,
  'English',
  'who-framed-roger-rabbit-nes/who-framed-roger-rabbit-nes.webp',
  '/games/covers/nes/who-framed-roger-rabbit-nes.webp',
  'who-framed-roger-rabbit-nes/who-framed-roger-rabbit-nes.nes',
  'nes',
  '',
  '["side-scrolling","8-bit","platforming precision","cartoonish"]',
  'Based on the hit film, this action-adventure game follows Eddie Valiant as he investigates Roger Rabbit''s framing for murder across Toontown''s dangerous streets.',
  '{"en":{"title":"Who Framed Roger Rabbit","description":"Based on the hit film, this action-adventure game follows Eddie Valiant as he investigates Roger Rabbit''s framing for murder across Toontown''s dangerous streets.","longDescription":["Features five distinct gameplay styles: driving, platforming, puzzle-solving, first-person investigation, and boss battles.","Includes cameos from over 20 classic cartoon characters like Mickey Mouse and Bugs Bunny (though altered for copyright reasons).","Notorious for its difficulty, particularly the unforgiving driving sections with instant-death obstacles."],"controls":{"D-Pad":"Move","A":"Jump","B":"Attack/Interact","Start":"Pause","Select":"Switch items"}}}',
  '[{"lang":"default","filename":"who-framed-roger-rabbit-nes.nes","localPath":"data/games/who-framed-roger-rabbit-nes/who-framed-roger-rabbit-nes.nes","r2Key":"who-framed-roger-rabbit-nes/who-framed-roger-rabbit-nes.nes","url":"https://classicgamezone.com/games/roms/nes/who-framed-roger-rabbit-nes.nes","size":131088,"status":"downloaded"}]',
  'published',
  'classicgamezone.com',
  '2026-07-14 23:09:38',
  '2026-07-14 23:09:38'
);
INSERT INTO games (
  slug, title, platform, year, genre, developer, publisher, series,
  isHack, language, coverUrl, imageUrl, defaultRom,
  ejsCore, ejsBiosUrl,
  tags, description, langs, roms,
  status, source, createdAt, updatedAt
) VALUES (
  'tecmo-super-bowl-iii-final-edition',
  'Tecmo Super Bowl III: Final Edition',
  'snes',
  1995,
  'sports',
  'tecmo',
  'tecmo',
  'tecmo-super-bowl',
  0,
  'English',
  'tecmo-super-bowl-iii-final-edition/tecmo-super-bowl-iii-final-edition.webp',
  '/games/covers/snes/tecmo-super-bowl-iii-final-edition.webp',
  'tecmo-super-bowl-iii-final-edition/tecmo-super-bowl-iii-final-edition.smc',
  'snes',
  '',
  '[{"name":"8-bit","count":200},{"name":"retro 3D","count":94},{"name":"side-scrolling","count":87},{"name":"boss fights","count":71},{"name":"platforming precision","count":62},{"name":"PvP","count":55},{"name":"co-op","count":45},{"name":"puzzle-solving mechanics","count":40},{"name":"arena battles","count":39},{"name":"competitive","count":27},{"name":"vehicles","count":27},{"name":"casual play","count":27},{"name":"sports","count":25},{"name":"turn-based","count":23},{"name":"cartoonish","count":22},{"name":"vibrant colors","count":21},{"name":"time attack","count":19},{"name":"exploration","count":19},{"name":"hardcore","count":17},{"name":"beat ''em up","count":16}]',
  'Tecmo Super Bowl III: Final Edition is the 1995 culmination of Tecmo''s football series for SNES, featuring updated 1994 NFL rosters, expanded playbooks, and new gameplay mechanics. As the last officially licensed Tecmo NFL game until 2020, it introduced franchise modes, two-player cooperative play, and enhanced AI that made it the most sophisticated entry in the classic series.',
  '{"en":{"title":"Tecmo Super Bowl III: Final Edition","description":"Tecmo Super Bowl III: Final Edition is the 1995 culmination of Tecmo''s football series for SNES, featuring updated 1994 NFL rosters, expanded playbooks, and new gameplay mechanics. As the last officially licensed Tecmo NFL game until 2020, it introduced franchise modes, two-player cooperative play, and enhanced AI that made it the most sophisticated entry in the classic series.","longDescription":["Building on its NES predecessors, Final Edition delivered the most complete football simulation of its era with all 28 NFL teams and their actual 1994 rosters. The game introduced ''Coach Mode'' for strategic play-calling, a full 17-week season with injuries and trades, and situational substitutions that mirrored real NFL strategy.","The gameplay refined Tecmo''s signature arcade-style action with new passing mechanics, special team plays, and defensive audibles. Players could now execute no-huddle offenses, call hot routes, and utilize an expanded roster of 53 players per team - a first for console football games.","Though overshadowed by emerging 32-bit football titles, Tecmo Super Bowl III remains a beloved classic for its perfect balance of accessibility and depth. Its legacy lives on through modding communities that continue updating rosters decades after release."],"controls":{"D-Pad":"Move Player","Y":"Pass/Select","B":"Run/Cancel","A":"Switch Player","X":"Dive/Juke","L":"Audible","R":"Turbo","Start":"Pause","Select":"Playbook"}}}',
  '[{"lang":"default","filename":"tecmo-super-bowl-iii-final-edition.smc","localPath":"data/games/tecmo-super-bowl-iii-final-edition/tecmo-super-bowl-iii-final-edition.smc","r2Key":"tecmo-super-bowl-iii-final-edition/tecmo-super-bowl-iii-final-edition.smc","url":"https://classicgamezone.com/games/roms/snes/tecmo-super-bowl-iii-final-edition.smc","size":954299,"status":"downloaded"}]',
  'published',
  'classicgamezone.com',
  '2026-07-14 23:09:38',
  '2026-07-14 23:09:38'
);
INSERT INTO games (
  slug, title, platform, year, genre, developer, publisher, series,
  isHack, language, coverUrl, imageUrl, defaultRom,
  ejsCore, ejsBiosUrl,
  tags, description, langs, roms,
  status, source, createdAt, updatedAt
) VALUES (
  'rise-of-the-robots',
  'Rise of the Robots',
  'snes',
  1994,
  'fighting',
  'mirage-technologies',
  'acclaim-entertainment',
  'rise-of-the-robots',
  0,
  'English',
  'rise-of-the-robots/rise-of-the-robots.webp',
  '/games/covers/snes/rise-of-the-robots.webp',
  'rise-of-the-robots/rise-of-the-robots.smc',
  'snes',
  '',
  '[{"name":"8-bit","count":200},{"name":"retro 3D","count":94},{"name":"side-scrolling","count":87},{"name":"boss fights","count":71},{"name":"platforming precision","count":62},{"name":"PvP","count":55},{"name":"co-op","count":45},{"name":"puzzle-solving mechanics","count":40},{"name":"arena battles","count":39},{"name":"competitive","count":27},{"name":"vehicles","count":27},{"name":"casual play","count":27},{"name":"sports","count":25},{"name":"turn-based","count":23},{"name":"cartoonish","count":22},{"name":"vibrant colors","count":21},{"name":"time attack","count":19},{"name":"exploration","count":19},{"name":"hardcore","count":17},{"name":"beat ''em up","count":16}]',
  'A futuristic fighting game featuring robotic combatants with pre-rendered 3D graphics. Players battle through a tournament of advanced AI opponents in a dystopian robot uprising scenario.',
  '{"en":{"title":"Rise of the Robots","description":"A futuristic fighting game featuring robotic combatants with pre-rendered 3D graphics. Players battle through a tournament of advanced AI opponents in a dystopian robot uprising scenario.","longDescription":["Notable for its cutting-edge (at release) CGI visuals and digitized sound effects, though criticized for shallow gameplay mechanics.","Features seven selectable robot fighters, each with unique designs and limited special moves.","Includes a ''story mode'' where the player''s robot gains sentience and leads the robotic revolution against human oppressors."],"controls":{"D-Pad":"Move","Y":"High Punch","X":"Low Punch","B":"High Kick","A":"Low Kick","L":"Block","R":"Special Move","Start":"Pause","Select":"Taunt"}}}',
  '[{"lang":"default","filename":"rise-of-the-robots.smc","localPath":"data/games/rise-of-the-robots/rise-of-the-robots.smc","r2Key":"rise-of-the-robots/rise-of-the-robots.smc","url":"https://classicgamezone.com/games/roms/snes/rise-of-the-robots.smc","size":3027373,"status":"downloaded"}]',
  'published',
  'classicgamezone.com',
  '2026-07-14 23:09:38',
  '2026-07-14 23:09:38'
);
INSERT INTO games (
  slug, title, platform, year, genre, developer, publisher, series,
  isHack, language, coverUrl, imageUrl, defaultRom,
  ejsCore, ejsBiosUrl,
  tags, description, langs, roms,
  status, source, createdAt, updatedAt
) VALUES (
  '007-nightfire-gba',
  '007: Nightfire',
  'game-boy-advance',
  2002,
  'first-person-shooter',
  'jv-games',
  'electronic-arts',
  'james-bond',
  0,
  'English',
  '007-nightfire-gba/007-nightfire-gba.webp',
  '/games/covers/gba/007-nightfire-gba.webp',
  '007-nightfire-gba/007-nightfire-gba.gba',
  'nes',
  '',
  '["FPS","stealth","co-op","PvP","boss fights","mission-based","retro 3D","hardcore"]',
  'A portable first-person shooter adaptation of the console hit, featuring James Bond in a globe-trotting mission to stop a nuclear weapons conspiracy. Includes both story campaign and multiplayer modes.',
  '{"en":{"title":"007: Nightfire","description":"A portable first-person shooter adaptation of the console hit, featuring James Bond in a globe-trotting mission to stop a nuclear weapons conspiracy. Includes both story campaign and multiplayer modes.","longDescription":["Condenses the console experience into an isometric shooter format optimized for GBA hardware.","Features 10 campaign missions across diverse locales including Austria, Japan, and a space station.","Includes 4-player multiplayer via link cable with classic Bond characters as playable agents.","Equip Bond with signature gadgets like the wristwatch laser and Q-Claw grappling hook."],"controls":{"D-pad":"Move","A":"Shoot/Interact","B":"Aim/Secondary Fire","L":"Cycle Weapons","R":"Use Gadget","Start":"Pause/Menu"}}}',
  '[{"lang":"default","filename":"007-nightfire-gba.gba","localPath":"data/games/007-nightfire-gba/007-nightfire-gba.gba","r2Key":"007-nightfire-gba/007-nightfire-gba.gba","url":"https://roms.classicgamezone.com/gba/007-nightfire-gba.gba","size":8388608,"status":"downloaded"}]',
  'published',
  'classicgamezone.com',
  '2026-07-14 23:09:38',
  '2026-07-14 23:09:38'
);
INSERT INTO games (
  slug, title, platform, year, genre, developer, publisher, series,
  isHack, language, coverUrl, imageUrl, defaultRom,
  ejsCore, ejsBiosUrl,
  tags, description, langs, roms,
  status, source, createdAt, updatedAt
) VALUES (
  'wwe-survivor-series-gba',
  'WWE Survivor Series',
  'game-boy-advance',
  2004,
  'wrestling',
  'natsume',
  'thq',
  'wwe',
  0,
  'English',
  'wwe-survivor-series-gba/wwe-survivor-series-gba.webp',
  '/games/covers/gba/wwe-survivor-series-gba.webp',
  'wwe-survivor-series-gba/wwe-survivor-series-gba.gba',
  'nes',
  '',
  '["sports","8-bit","wrestling","competitive"]',
  'The official GBA adaptation of WWE''s classic elimination tag team event. Features 40+ WWE superstars from the Ruthless Aggression era including John Cena, Brock Lesnar, and The Undertaker in fast-paced 2D wrestling action.',
  '{"en":{"title":"WWE Survivor Series","description":"The official GBA adaptation of WWE''s classic elimination tag team event. Features 40+ WWE superstars from the Ruthless Aggression era including John Cena, Brock Lesnar, and The Undertaker in fast-paced 2D wrestling action.","longDescription":["Faithfully recreates the Survivor Series elimination match format with 5-on-5 and 4-on-4 tag team battles. Includes standard singles and hardcore matches.","Notable for its exaggerated sprite animations and signature move system allowing players to perform each wrestler''s iconic finishers.","Features a season mode where players compete through WWE''s pay-per-view calendar leading up to Survivor Series."],"controls":{"D-Pad":"Move wrestler","A":"Grapple/Strike","B":"Run/Irish whip","L":"Taunt/Special meter","R":"Block/Reversal","SELECT":"Switch targets (tag matches)","START":"Pause"}}}',
  '[{"lang":"default","filename":"wwe-survivor-series-gba.gba","localPath":"data/games/wwe-survivor-series-gba/wwe-survivor-series-gba.gba","r2Key":"wwe-survivor-series-gba/wwe-survivor-series-gba.gba","url":"https://roms.classicgamezone.com/gba/wwe-survivor-series-gba.gba","size":2471548,"status":"downloaded"}]',
  'published',
  'classicgamezone.com',
  '2026-07-14 23:09:38',
  '2026-07-14 23:09:38'
);
INSERT INTO games (
  slug, title, platform, year, genre, developer, publisher, series,
  isHack, language, coverUrl, imageUrl, defaultRom,
  ejsCore, ejsBiosUrl,
  tags, description, langs, roms,
  status, source, createdAt, updatedAt
) VALUES (
  'the-addams-family',
  'The Addams Family',
  'genesis',
  1992,
  'platformer',
  'ocean-software',
  'flying-edge',
  'the-addams-family',
  0,
  'English',
  'the-addams-family/the-addams-family.webp',
  '/games/covers/genesis/the-addams-family.webp',
  'the-addams-family/the-addams-family.md',
  'segaMD',
  '',
  '[{"name":"8-bit","count":200},{"name":"retro 3D","count":94},{"name":"side-scrolling","count":87},{"name":"boss fights","count":71},{"name":"platforming precision","count":62},{"name":"PvP","count":55},{"name":"co-op","count":45},{"name":"puzzle-solving mechanics","count":40},{"name":"arena battles","count":39},{"name":"competitive","count":27},{"name":"vehicles","count":27},{"name":"casual play","count":27},{"name":"sports","count":25},{"name":"turn-based","count":23},{"name":"cartoonish","count":22},{"name":"vibrant colors","count":21},{"name":"time attack","count":19},{"name":"exploration","count":19},{"name":"hardcore","count":17},{"name":"beat ''em up","count":16}]',
  'A platformer based on the 1991 film, where players control Gomez Addams through 18 spooky stages to rescue family members from the corrupt lawyer Tully Alford.',
  '{"en":{"title":"The Addams Family","description":"A platformer based on the 1991 film, where players control Gomez Addams through 18 spooky stages to rescue family members from the corrupt lawyer Tully Alford.","longDescription":["Features non-linear progression through the Addams mansion and surrounding areas, with each family member''s rescue unlocking new abilities.","Known for its authentic recreation of the film''s gothic atmosphere and Danny Elfman''s iconic theme adapted for the Genesis sound chip.","Considered one of the better licensed games of its era, praised for tight controls and creative level designs that capture the franchise''s macabre humor."],"controls":{"D-Pad":"Move","A":"Jump","B":"Attack","C":"Special Move","Start":"Pause"}}}',
  '[{"lang":"default","filename":"the-addams-family.md","localPath":"data/games/the-addams-family/the-addams-family.md","r2Key":"the-addams-family/the-addams-family.md","url":"https://classicgamezone.com/games/roms/genesis/the-addams-family.md","size":615620,"status":"downloaded"}]',
  'published',
  'classicgamezone.com',
  '2026-07-14 23:09:38',
  '2026-07-14 23:09:38'
);
INSERT INTO games (
  slug, title, platform, year, genre, developer, publisher, series,
  isHack, language, coverUrl, imageUrl, defaultRom,
  ejsCore, ejsBiosUrl,
  tags, description, langs, roms,
  status, source, createdAt, updatedAt
) VALUES (
  'strider-returns-journey-from-darkness',
  'Strider Returns: Journey from Darkness',
  'genesis',
  1992,
  'platformer',
  'tiertex-design-studios',
  'u-s-gold',
  'strider',
  0,
  'English',
  'strider-returns-journey-from-darkness/strider-returns-journey-from-darkness.webp',
  '/games/covers/genesis/strider-returns-journey-from-darkness.webp',
  'strider-returns-journey-from-darkness/strider-returns-journey-from-darkness.md',
  'segaMD',
  '',
  '["side-scrolling","8-bit","platforming precision","ninja"]',
  'A non-canonical sequel to the original Strider game, featuring new protagonist Strider Hiryu II battling through futuristic environments with his plasma cypher weapon. Despite the title, this was developed without involvement from Capcom.',
  '{"en":{"title":"Strider Returns: Journey from Darkness","description":"A non-canonical sequel to the original Strider game, featuring new protagonist Strider Hiryu II battling through futuristic environments with his plasma cypher weapon. Despite the title, this was developed without involvement from Capcom.","longDescription":["Features 12 levels across diverse locales including a moving train, undersea base, and orbital space station.","Expands the original''s mechanics with new power-ups including temporary invincibility and enhanced cypher attacks.","Criticized for sluggish controls and unfair difficulty spikes compared to the arcade original.","Includes password save system and two difficulty settings to accommodate different skill levels."],"controls":{"←→":"Move","↑":"Jump","↓":"Crouch","A":"Attack (Cypher)","B":"Jump","C":"Special Attack","Start":"Pause","Mode":"Change Weapon (Select)"}}}',
  '[{"lang":"default","filename":"strider-returns-journey-from-darkness.md","localPath":"data/games/strider-returns-journey-from-darkness/strider-returns-journey-from-darkness.md","r2Key":"strider-returns-journey-from-darkness/strider-returns-journey-from-darkness.md","url":"https://classicgamezone.com/games/roms/genesis/strider-returns-journey-from-darkness.md","size":120614,"status":"downloaded"}]',
  'published',
  'classicgamezone.com',
  '2026-07-14 23:09:38',
  '2026-07-14 23:09:38'
);
INSERT INTO games (
  slug, title, platform, year, genre, developer, publisher, series,
  isHack, language, coverUrl, imageUrl, defaultRom,
  ejsCore, ejsBiosUrl,
  tags, description, langs, roms,
  status, source, createdAt, updatedAt
) VALUES (
  'dungeons-and-dragons-shadow-over-mystara',
  'Dungeons & Dragons: Shadow over Mystara',
  'arcade',
  1996,
  'beat-em-up',
  'capcom',
  'capcom',
  'dungeons-and-dragons',
  0,
  'English',
  'dungeons-and-dragons-shadow-over-mystara/dungeons-and-dragons-shadow-over-mystara.webp',
  '/games/covers/arcade/dungeons-and-dragons-shadow-over-mystara.webp',
  'dungeons-and-dragons-shadow-over-mystara/ddsom.zip',
  'arcade',
  '',
  '["side-scrolling","beat ''em up","8-bit","co-op","combo system"]',
  'Capcom''s legendary arcade beat ''em up/RPG hybrid set in the Dungeons & Dragons universe. Features deep character customization, magic spells, and branching paths with multiple endings.',
  '{"en":{"title":"Dungeons & Dragons: Shadow over Mystara","description":"Capcom''s legendary arcade beat ''em up/RPG hybrid set in the Dungeons & Dragons universe. Features deep character customization, magic spells, and branching paths with multiple endings.","longDescription":["Expands upon Tower of Doom with 6 playable classes (Fighter, Elf, Dwarf, Cleric, Magic User, Thief) each with unique abilities and equipment progression.","Introduces a real-time inventory system where players can swap weapons/items mid-combat and use environmental objects as weapons.","Contains over 30 magic spells and dozens of hidden secrets including alternate bosses and secret areas accessible through D&D-style puzzle solving."],"controls":{"Joystick":"Move","Button 1":"Attack","Button 2":"Jump","Button 3":"Use Item/Spell","Button 4":"Inventory","Start":"Insert Coin"}}}',
  '[{"lang":"default","filename":"ddsom.zip","localPath":"data/games/dungeons-and-dragons-shadow-over-mystara/ddsom.zip","r2Key":"dungeons-and-dragons-shadow-over-mystara/ddsom.zip","url":"https://roms.classicgamezone.com/arcade/ddsom.zip","size":16975285,"status":"downloaded"}]',
  'published',
  'classicgamezone.com',
  '2026-07-14 23:09:38',
  '2026-07-14 23:09:38'
);
INSERT INTO games (
  slug, title, platform, year, genre, developer, publisher, series,
  isHack, language, coverUrl, imageUrl, defaultRom,
  ejsCore, ejsBiosUrl,
  tags, description, langs, roms,
  status, source, createdAt, updatedAt
) VALUES (
  'rockman-the-power-battle',
  'Rockman: The Power Battle',
  'arcade',
  1995,
  'fighting',
  'capcom',
  'capcom',
  'mega-man',
  0,
  'English',
  'rockman-the-power-battle/rockman-the-power-battle.webp',
  '/games/covers/arcade/rockman-the-power-battle.webp',
  'rockman-the-power-battle/megaman.zip',
  'arcade',
  '',
  '["side-scrolling","platforming precision","8-bit","boss fights","weapon upgrades"]',
  'A 1995 arcade-exclusive fighting game featuring Mega Man characters in head-to-head battles. Players select from Mega Man, Proto Man, or Bass to defeat Robot Masters from Mega Man 1-7 in a tournament-style format with power-up systems.',
  '{"en":{"title":"Rockman: The Power Battle","description":"A 1995 arcade-exclusive fighting game featuring Mega Man characters in head-to-head battles. Players select from Mega Man, Proto Man, or Bass to defeat Robot Masters from Mega Man 1-7 in a tournament-style format with power-up systems.","longDescription":["Developed as part of Capcom''s CPS-2 arcade lineup, this game distilled Mega Man''s core gameplay into competitive 1-on-1 matches with simplified controls.","Unique ''Power Battle'' system allows characters to steal weapons from defeated bosses, similar to main series games but adapted for versus play.","Though never ported to consoles, it gained cult status for its rare arcade-exclusive roster including Bass (Forte) before his console debut."],"controls":{"Joystick":"Movement","Button 1":"Jump","Button 2":"Shoot","Button 3":"Slide (Mega Man/Proto Man)","Button 4":"Dash (Bass)","Button 1+2":"Charge Shot (when weapon energy available)"}}}',
  '[{"lang":"default","filename":"megaman.zip","localPath":"data/games/rockman-the-power-battle/megaman.zip","r2Key":"rockman-the-power-battle/megaman.zip","url":"https://roms.classicgamezone.com/arcade/megaman.zip","size":3301559,"status":"downloaded"}]',
  'published',
  'classicgamezone.com',
  '2026-07-14 23:09:38',
  '2026-07-14 23:09:38'
);
INSERT INTO games (
  slug, title, platform, year, genre, developer, publisher, series,
  isHack, language, coverUrl, imageUrl, defaultRom,
  ejsCore, ejsBiosUrl,
  tags, description, langs, roms,
  status, source, createdAt, updatedAt
) VALUES (
  'tsumi-to-batsu-hoshi-no-keishousha',
  'Sin and Punishment: Successor of the Earth',
  'nintendo-64',
  2000,
  'adventure',
  'human-entertainment',
  'human-entertainment',
  'tsumi-to-batsu',
  0,
  'English',
  'tsumi-to-batsu-hoshi-no-keishousha/tsumi-to-batsu-hoshi-no-keishousha.webp',
  '/games/covers/n64/tsumi-to-batsu-hoshi-no-keishousha.webp',
  'tsumi-to-batsu-hoshi-no-keishousha/sin.n64',
  'nes',
  '',
  '["rail shooter","boss fights","quick reflexes","retro 3D","hardcore"]',
  'A groundbreaking rail shooter/visual novel hybrid with frenetic on-rails combat and a deep sci-fi storyline. Set in a dystopian future where mutated humans battle for survival, featuring innovative dual-stick controls years before their mainstream adoption.',
  '{"en":{"title":"Sin and Punishment: Successor of the Earth","description":"A groundbreaking rail shooter/visual novel hybrid with frenetic on-rails combat and a deep sci-fi storyline. Set in a dystopian future where mutated humans battle for survival, featuring innovative dual-stick controls years before their mainstream adoption.","longDescription":["Developed by the team behind Clock Tower, blending shooting action with visual novel storytelling techniques.","Pioneered dual-analog stick controls for simultaneous movement and aiming - a scheme later popularized by Halo.","Initially a commercial failure but gained cult status, leading to a 2007 Wii sequel and eventual worldwide Virtual Console release."],"controls":{"Control Stick":"Move character","C Buttons":"Aim/shoot","A Button":"Jump","B Button":"Special attack","Z Trigger":"Lock-on"}}}',
  '[{"lang":"en","filename":"sin.n64","localPath":"data/games/tsumi-to-batsu-hoshi-no-keishousha/sin.n64","r2Key":"tsumi-to-batsu-hoshi-no-keishousha/sin.n64","url":"https://roms.classicgamezone.com/n64/sin.n64","size":33554432,"status":"downloaded"},{"lang":"ja","filename":"sin-ja.n64","localPath":"data/games/tsumi-to-batsu-hoshi-no-keishousha/sin-ja.n64","r2Key":"tsumi-to-batsu-hoshi-no-keishousha/sin-ja.n64","url":"https://roms.classicgamezone.com/n64/sin-ja.n64","size":33554432,"status":"downloaded"},{"lang":"zh-cn","filename":"sin-cn.n64","localPath":"data/games/tsumi-to-batsu-hoshi-no-keishousha/sin-cn.n64","r2Key":"tsumi-to-batsu-hoshi-no-keishousha/sin-cn.n64","url":"https://roms.classicgamezone.com/n64/sin-cn.n64","size":33636352,"status":"downloaded"}]',
  'published',
  'classicgamezone.com',
  '2026-07-14 23:09:38',
  '2026-07-14 23:09:38'
);
INSERT INTO games (
  slug, title, platform, year, genre, developer, publisher, series,
  isHack, language, coverUrl, imageUrl, defaultRom,
  ejsCore, ejsBiosUrl,
  tags, description, langs, roms,
  status, source, createdAt, updatedAt
) VALUES (
  'san-francisco-rush-extreme-racing-n64',
  'San Francisco Rush: Extreme Racing',
  'nintendo-64',
  1997,
  'racing',
  'atari-games',
  'midway-games',
  'rush',
  0,
  'English',
  'san-francisco-rush-extreme-racing-n64/san-francisco-rush-extreme-racing-n64.webp',
  '/games/covers/n64/san-francisco-rush-extreme-racing-n64.webp',
  'san-francisco-rush-extreme-racing-n64/san-francisco-rush-extreme-racing-n64.n64',
  'nes',
  '',
  '["vehicle segments","8-bit","time attack","track editor"]',
  'An arcade-style racing game featuring exaggerated physics, stunt jumps, and hidden shortcuts through a scaled-down recreation of San Francisco. Choose from 8 high-performance cars and race against traffic in 5 iconic districts.',
  '{"en":{"title":"San Francisco Rush: Extreme Racing","description":"An arcade-style racing game featuring exaggerated physics, stunt jumps, and hidden shortcuts through a scaled-down recreation of San Francisco. Choose from 8 high-performance cars and race against traffic in 5 iconic districts.","longDescription":["Notable for its ''Crash Mode'' where players aimed to cause maximum vehicular destruction. The game''s deformable car models and environmental damage were groundbreaking for 1997.","Featured a full recreation of the Golden Gate Bridge that could be jumped at high speeds. Hidden areas included Alcatraz Island and secret underground tunnels accessible through clever shortcuts.","The N64 version ran at a smooth 30fps while maintaining the arcade original''s sense of speed. Later received a Japan-exclusive sequel called ''Rush 2: Extreme Racing USA'' with additional tracks."],"controls":{"Control Stick":"Steer","A":"Accelerate","B":"Brake/Reverse","C Buttons":"Camera Adjust","Z":"Handbrake","R":"Turbo (if equipped)","Start":"Pause"}}}',
  '[{"lang":"default","filename":"san-francisco-rush-extreme-racing-n64.n64","localPath":"data/games/san-francisco-rush-extreme-racing-n64/san-francisco-rush-extreme-racing-n64.n64","r2Key":"san-francisco-rush-extreme-racing-n64/san-francisco-rush-extreme-racing-n64.n64","url":"https://roms.classicgamezone.com/n64/san-francisco-rush-extreme-racing-n64.n64","size":7960610,"status":"downloaded"}]',
  'published',
  'classicgamezone.com',
  '2026-07-14 23:09:38',
  '2026-07-14 23:09:38'
);
INSERT INTO games (
  slug, title, platform, year, genre, developer, publisher, series,
  isHack, language, coverUrl, imageUrl, defaultRom,
  ejsCore, ejsBiosUrl,
  tags, description, langs, roms,
  status, source, createdAt, updatedAt
) VALUES (
  'toy-story-2-buzz-lightyear-to-the-rescue',
  'Toy Story 2: Buzz Lightyear to the Rescue',
  'playstation',
  1999,
  'platformer',
  'travellers-tales',
  'activision',
  'toy-story',
  0,
  'English',
  'toy-story-2-buzz-lightyear-to-the-rescue/toy-story-2-buzz-lightyear-to-the-rescue.webp',
  '/games/covers/ps/toy-story-2-buzz-lightyear-to-the-rescue.webp',
  'toy-story-2-buzz-lightyear-to-the-rescue/buzz-lightyear.7z',
  'psx',
  '/bios/scph1001.bin',
  '["3D platforming","collectibles","vibrant colors","cartoonish","retro 3D"]',
  'Based on the Disney/Pixar film, this 3D platformer follows Buzz Lightyear''s quest to rescue Woody from the toy collector Al McWhiggin. Features voice acting from the original movie cast and levels inspired by key film locations.',
  '{"en":{"title":"Toy Story 2: Buzz Lightyear to the Rescue","description":"Based on the Disney/Pixar film, this 3D platformer follows Buzz Lightyear''s quest to rescue Woody from the toy collector Al McWhiggin. Features voice acting from the original movie cast and levels inspired by key film locations.","longDescription":["The game expands the movie''s storyline with original levels like Al''s Toy Barn and Pizza Planet, incorporating classic platforming mechanics with toy-themed power-ups.","Notable for its faithful character animations and humor, including Buzz''s special moves like rocket jumps and laser attacks. Collectible Pizza Planet tokens unlock bonus content.","Received praise for capturing the film''s charm while offering challenging gameplay. The PlayStation version was considered the definitive edition with enhanced graphics and audio."],"controls":{"D-Pad":"Move","X":"Jump","Square":"Punch","Triangle":"Laser Attack","Circle":"Action/Interact"}}}',
  '[{"lang":"default","filename":"buzz-lightyear.7z","localPath":"data/games/toy-story-2-buzz-lightyear-to-the-rescue/buzz-lightyear.7z","r2Key":"toy-story-2-buzz-lightyear-to-the-rescue/buzz-lightyear.7z","url":"https://roms.classicgamezone.com/ps/buzz-lightyear.7z","size":12341809,"status":"downloaded"}]',
  'published',
  'classicgamezone.com',
  '2026-07-14 23:09:38',
  '2026-07-14 23:09:38'
);
INSERT INTO games (
  slug, title, platform, year, genre, developer, publisher, series,
  isHack, language, coverUrl, imageUrl, defaultRom,
  ejsCore, ejsBiosUrl,
  tags, description, langs, roms,
  status, source, createdAt, updatedAt
) VALUES (
  'bushido-blade-2-ps',
  'Bushido Blade 2',
  'playstation',
  1998,
  'fighting',
  'light-weight',
  'squaresoft',
  'undefined',
  0,
  'English',
  'bushido-blade-2-ps/bushido-blade-2-ps.webp',
  'https://classicgamezone.com/games/covers/ps/bushido-blade-2-ps.webp',
  NULL,
  'psx',
  '/bios/scph1001.bin',
  '[{"name":"8-bit","count":200},{"name":"retro 3D","count":94},{"name":"side-scrolling","count":87},{"name":"boss fights","count":71},{"name":"platforming precision","count":62},{"name":"PvP","count":55},{"name":"co-op","count":45},{"name":"puzzle-solving mechanics","count":40},{"name":"arena battles","count":39},{"name":"competitive","count":27},{"name":"vehicles","count":27},{"name":"casual play","count":27},{"name":"sports","count":25},{"name":"turn-based","count":23},{"name":"cartoonish","count":22},{"name":"vibrant colors","count":21},{"name":"time attack","count":19},{"name":"exploration","count":19},{"name":"hardcore","count":17},{"name":"beat ''em up","count":16}]',
  'The brutal sequel enhancing the revolutionary one-hit-kill combat system with new dismemberment mechanics, 10 playable characters, and expanded 3D environments. Features a gripping revenge storyline across 60 missions and new ''Bloodlust Mode'' for no-holds-barred combat.',
  '{"en":{"title":"Bushido Blade 2","description":"The brutal sequel enhancing the revolutionary one-hit-kill combat system with new dismemberment mechanics, 10 playable characters, and expanded 3D environments. Features a gripping revenge storyline across 60 missions and new ''Bloodlust Mode'' for no-holds-barred combat.","longDescription":["Introduces limb-specific damage modeling - arms can be severed mid-battle, forcing players to fight one-handed, while leg wounds dramatically reduce mobility.","Expands weapon selection to 15 types including dual-wielding katanas, chain weapons, and European-style broadswords, each with unique move sets and realistic weight physics.","Dramatic ''Blade Lock'' system creates intense close-quarters standoffs where precise button inputs decide life or death.","Features destructible environments where bamboo forests can be sliced down and castle walls crumble during combat.","Includes 4-player tournament mode via PlayStation Multi-Tap support, pushing the hardware''s capabilities with fluid 60fps duels."],"controls":{"D-Pad":"Move","Left Stick":"Move (DualShock)","○":"Horizontal Slash","×":"Vertical Slash","□":"Kick","△":"Change Stance","L1":"Block/Parry","R1":"Lock-on","L2":"Feint/Dodge","R2":"Sheathe Weapon","Start":"Pause","Select":"Toggle Blood Effects"}}}',
  '[]',
  'published',
  'classicgamezone.com',
  '2026-07-14 23:09:38',
  '2026-07-14 23:09:38'
);

COMMIT;
